#!/bin/bash
set -x
pwd
echo $DRUPAL_TI_WEBSERVER_URL
echo $DRUPAL_TI_WEBSERVER_PORT
echo $DRUPAL_TI_DRUPAL_DIR
echo $DRUPAL_TI_BEHAT_DIR
cd "$DRUPAL_TI_DRUPAL_DIR/$DRUPAL_TI_MODULES_PATH/$DRUPAL_TI_MODULE_NAME/$DRUPAL_TI_BEHAT_DIR"

 