<?php
/**
* @file
* A description of what your module does.
*/
/*another comment*/
/**
 * @file
 * Contains database schema for the Mentions module.
 */
use Drupal\Core\Url;
use Drupal\mentions\Entity;
use Drupal\field;



function mentions_theme() {
  return array(
    'mentions' => array(
      'render element' => 'userintext'
    )
  );

}

function template_preprocess_mentions(&$variables) {
  $settings = \Drupal::config('mentions.mentions');
  $output_settings = $settings->get('output');
  $user = $variables['userintext']['#user'];

  foreach (array('text', 'link') as $type) {
    if (!empty($output_settings[$type])) {
      //$type = token_replace($output_settings[$type], array('user' => $user));
      $what = \Drupal::token()->replace($output_settings[$type], array('user' => $user));
      if ($type == 'text')
        $text = $what;
     else
       $link = $what;
    }
  }


  $userpageurl = Url::fromUri('base://' . $link);
    $variables['userid'] = $user->id();
    $variables['link'] = \Drupal::l($output_settings['prefix'] . $text . $output_settings['suffix'], $userpageurl, array(
        'attributes' => array(
            'class' => 'mentions mentions-' . $user->id(),
            'title' => $text,
        )));

}

/**
 *  Implements hook_entity_insert().
 */
function mentions_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {

  $typeid = $entity->getEntityTypeId();
  if ($entity->getEntityTypeId() != 'node' ) return;

  $id = $entity->id();
  $type = $entity->getEntityType();
  $field_definitions = $entity->getFieldDefinitions();
  $fields_with_text = array();
  foreach($field_definitions as $field_definition ) {
    if ($field_definition instanceof field\Entity\FieldConfig) {
      array_push($fields_with_text, $field_definition->field_name);
    }
  }


  foreach($fields_with_text as $textfield) {
    $boo = $entity->get($textfield);
    $value = $boo->value;
    $filter_mentions = new \Drupal\mentions\Plugin\Filter\FilterMentions(array(),'',null);
    $mentions = $filter_mentions->mentions_get_mentions($value);

  }
  //$body_field_definition = $entity->getFieldDefinition('body');
  //$body_field_type = $body_field_definition->field_type;


  $mention = entity_create('mention', array('auid'=> 1));
  $mention->save();
}